# Hello bienvenue dans le docker compose
# CHANGEZ LES MOTS DE PASSE !!!
services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=glpidb
      - MARIADB_USER=glpi_user
      - MARIADB_PASSWORD=glpi
    volumes:
      - mariadb_data:/var/lib/mysql

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - glpi_files:/var/www/html/glpi/files
      - glpi_plugins:/var/www/html/glpi/plugins

volumes:
  mariadb_data:
  glpi_files:
  glpi_plugins:
